robot_radius: 0.2
obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.36
static_layer:
  enabled: true
max_obstacle_height: 0.8
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, 
   topic: /scan, 
   marking: true, 
   clearing: true, 
   expected_update_rate: 0}
   
