obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.19
robot_radius: 0.175
inflation_radius: 0.5
transform_tolerance: 0.2        #变换容忍时间
observation_sources: scan       #观测源
scan:
   data_type: LaserScan         #数据类型
   topic: /scan                 #话题名
   sensor_frame: laser_link     #传感器坐标系
   marking: true                #是否利用检测结果标记障碍物,false-> 即使检测到障碍物，也不更新到代价地图
   clearing: true               #是否利用检测结果清除障碍物,false-> 代价地图中已存在的障碍物,当前即使未检测到，也不清除
   expected_update_rate: 5      #期望更新频率
   inf_is_valid: true           #无限值是否有效
   max_obstacle_height: 0.6     #最大障碍物高度
   min_obstacle_height: 0.0     #最小障碍物高度
   observation_persistence: 0.0 #观测维持时间
