global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true        #参数用来决定代价地图是否需要根据map_server提供的地图信息进行初始化，
                           #如果不需要使用已有的地图或者map_server，最好将该参数设置为false
                           #全局代价地图须包含静态地图,否则无法进行全局路径规划
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap
   
   #下列参数拷贝自costmap_common_params,目的使局部代价地图与全局代价地图应用不同的参数
   #参数详解见costmap_common_params.yaml
   obstacle_range: 2.5       #障碍物检测范围,范围内的障碍物将被更新到代价地图
   raytrace_range: 3.0      #激光束范围,在范围内清除代价地图中不存在的障碍物
   robot_radius: 0.175       #用于计算机器人脚印
   inflation_radius: 0.7     #用于障碍物膨胀,全局代价地图大尺度膨胀,确保全局路径不靠近墙壁
   max_obstacle_height: 0.6
   min_obstacle_height: 0.0
   observation_sources: scan
   scan:
     data_type: LaserScan
     topic: /scan
     marking: true            #若全局代价地图不更新障碍物信息,当机器人被局部障碍物阻碍时无法重新进行有效的全局规划
     clearing: true
     expected_update_rate: 5
